substitutions:
  device_name: "D1 Mini"
esphome:
  name: d1mini

esp8266:
  board: d1_mini

logger:

api:
  services:
    - service: hunter_start_program
      variables:
        program: int
      then:
      - lambda:  |-
            id(hunterremote).startProgram(program);
    - service: hunter_run_zone
      variables:
        zone_id: int
		runmins: int
      then:
      - lambda: |-
            id(hunterremote).startZone(zone_id, runmins);
    - service: hunter_stop_zone
      variables:
        zone_id: int
      then:
      - lambda: |-
            id(hunterremote).stopZone(zone_id);

ota:
  platform: esphome
  password: ""



wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${device_name} Fallback Hotspot"

captive_portal:

external_components:
  - source: github://andrastakacs/hunter-remote@main
    components: [hunter_remote]
hunter_remote:
  id: hunterremote
  pin: D0

